### ISSUE TITLE
Not working with python 3.6

### ISSUE THREAD

**Issue by shahroze90** [dRoje/pipe-proxy#1]
When i try importing pipeproxy, i get the following error:

from pipeproxy import proxy
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 19, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\Shahroze Tariq\AppData\Local\Programs\Python\Python36\lib\site-packages\pipeproxy\proxy.py", line 3, in <module>
    from lib.proxyListener.proxyListener import ProxyListener
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 19, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'lib'

**Comment by tiholic** [comment]
@dRoje I have made changes for this to work with python 3.6, I can push them to a new branch if you can add me to the project

**Comment by Droid997** [comment]
Does it support python 3.6 now ? I get the below error
Traceback (most recent call last):
  File "/home/dishanth/.local/lib/python3.6/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/dishanth/Documents/SURT/SapConnector/app.py", line 1, in <module>
    from surt import app
  File "/home/dishanth/Documents/SURT/SapConnector/surt/__init__.py", line 16, in <module>
    from pipeproxy import proxy
  File "/home/dishanth/.local/lib/python3.6/site-packages/pipeproxy/proxy.py", line 3, in <module>
    from lib.proxyListener.proxyListener import ProxyListener
